### ISSUE TITLE
safari on iphone

### ISSUE THREAD

**Issue by jesspaget** [anna-trojanowska/annatrojanowska.ca#10]
![untitled-11](https://cloud.githubusercontent.com/assets/6373211/10368075/965beeba-6da1-11e5-8a96-244ba2f7859c.jpg)

Ya already know this but I'm gunna put it anyways :3 
try overflow: hidden on the body! or overflow-x: hidden

**Comment by charlie-quinn** [comment]
_Microsoft Edge - mobile_
Also, try to keep your name with "about" (there are keep options for HTML).
& scale leading down a bit ^ :)

**Comment by anna-trojanowska** [comment]
thank you!
