### ISSUE TITLE
Flower Arch & text (Safari 9 L Screen)

### ISSUE THREAD

**Issue by valeriebordeleau** [anna-trojanowska/annatrojanowska.ca#2]
![screen shot 2015-10-08 at 9 06 53 am](https://cloud.githubusercontent.com/assets/6373198/10367047/2624b046-6d9c-11e5-804a-4d795673a1df.png)

I'm pretty sure you're already working on this but the flower arch cuts off some of your text. Maybe there's  a way you split it in half and create two flexible background images?

**Comment by ahmedzein** [comment]
Difficult to read text on mobile

**Comment by annamisak** [comment]
On Android 5/ Chrome, there is a lot of empty space between the arch and your name

**Comment by marisabivi** [comment]
Text overlaps arch in Opera Mini as well.
