### ISSUE TITLE
Extra scroll bar  (Android 5/ Chrome)

### ISSUE THREAD

**Issue by annamisak** [anna-trojanowska/annatrojanowska.ca#4]
Your page has an extra scroll bar at bottom of page.

**Comment by devonash** [comment]
![screen shot 2015-10-08 at 9 25 25 am](https://cloud.githubusercontent.com/assets/6373210/10367465/a92e7074-6d9e-11e5-9497-055e1e3414a0.png)

Extra scroll bar at the bottom of the page on small screen (safari 7)
