### ISSUE TITLE
Android 5.0.1 Mobile

### ISSUE THREAD

**Issue by jazdown** [anna-trojanowska/annatrojanowska.ca#6]
There is a tiny 
![screenshot_2015-10-08-08-49-07](https://cloud.githubusercontent.com/assets/6373208/10367642/99eb8290-6d9f-11e5-883a-0136b7c8ad75.png)
side scroll on all of your pages on mobile android. (You can see it in the pictures by the bottom scroll bar)

**Comment by kayleemenard** [comment]
In Firefox on the Nexus 4, there's no side scroll, but there's an obvious (not so obvious with the screenshot on a white background) gap for both portrait and landscape views. 

![2015-10-08 14 00 11](https://cloud.githubusercontent.com/assets/6373202/10368621/3a6cd3c8-6da4-11e5-9c62-cbc3bdd64f00.png)
![2015-10-08 14 00 03](https://cloud.githubusercontent.com/assets/6373202/10368624/3c212eb2-6da4-11e5-8587-e66cfdcd6a14.png)

_side-note: your nav looks a little off, is it suppose to be centered, or floating to the right?_
_side-side-note: Is it possible to put your name on top of the flower wreath?_
