### ISSUE TITLE
Firefox Testing  

### ISSUE THREAD

**Issue by paisley-laurenzio** [anna-trojanowska/annatrojanowska.ca#9]
You might want to adjust the placement of the words on the banner because they get a bit cut off when the screen size scales. 

![screen shot 2015-10-08 at 9 36 27 am](https://cloud.githubusercontent.com/assets/6371044/10367767/4c3a4f76-6da0-11e5-8aa9-8662a11d0fc4.png)

Just be careful that when you hover on the illustration of you on the home screen on a small screen it doesn't lift too high.
![screen shot 2015-10-08 at 9 37 22 am](https://cloud.githubusercontent.com/assets/6371044/10367768/4c45feb6-6da0-11e5-8284-582223d9ff4a.png)

Looks good though!!

**Comment by anna-trojanowska** [comment]
Hey! Ive changed the whole thing entirely... hope it works now. Thanks!
